# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hist_matching.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1273, 694)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(90, 30, 321, 581))
        self.groupBox.setObjectName("groupBox")
        self.img_input = QtWidgets.QLabel(self.groupBox)
        self.img_input.setGeometry(QtCore.QRect(70, 10, 171, 251))
        self.img_input.setText("")
        self.img_input.setObjectName("img_input")
        self.hist_input = QtWidgets.QLabel(self.groupBox)
        self.hist_input.setGeometry(QtCore.QRect(10, 270, 291, 291))
        self.hist_input.setText("")
        self.hist_input.setObjectName("hist_input")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(450, 30, 321, 581))
        self.groupBox_2.setObjectName("groupBox_2")
        self.img_target = QtWidgets.QLabel(self.groupBox_2)
        self.img_target.setGeometry(QtCore.QRect(80, 10, 171, 251))
        self.img_target.setText("")
        self.img_target.setObjectName("img_target")
        self.hist_target = QtWidgets.QLabel(self.groupBox_2)
        self.hist_target.setGeometry(QtCore.QRect(20, 270, 291, 291))
        self.hist_target.setText("")
        self.hist_target.setObjectName("hist_target")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(260, 420, 291, 291))
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(830, 30, 321, 581))
        self.groupBox_4.setObjectName("groupBox_4")
        self.img_result = QtWidgets.QLabel(self.groupBox_4)
        self.img_result.setGeometry(QtCore.QRect(80, 10, 171, 251))
        self.img_result.setText("")
        self.img_result.setObjectName("img_result")
        self.hist_result = QtWidgets.QLabel(self.groupBox_4)
        self.hist_result.setGeometry(QtCore.QRect(10, 270, 291, 291))
        self.hist_result.setText("")
        self.hist_result.setObjectName("hist_result")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1273, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.equalizeHist = QtWidgets.QToolBar(MainWindow)
        self.equalizeHist.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.equalizeHist.setObjectName("equalizeHist")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.equalizeHist)
        self.actionOpen_Input = QtWidgets.QAction(MainWindow)
        self.actionOpen_Input.setObjectName("actionOpen_Input")
        self.actionOpen_Target = QtWidgets.QAction(MainWindow)
        self.actionOpen_Target.setObjectName("actionOpen_Target")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionEqualize_Histogram = QtWidgets.QAction(MainWindow)
        self.actionEqualize_Histogram.setObjectName("actionEqualize_Histogram")
        self.menuFile.addAction(self.actionOpen_Input)
        self.menuFile.addAction(self.actionOpen_Target)
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.equalizeHist.addAction(self.actionEqualize_Histogram)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Input"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Target"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Result"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.equalizeHist.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionOpen_Input.setText(_translate("MainWindow", "Open Input"))
        self.actionOpen_Target.setText(_translate("MainWindow", "Open Target"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionEqualize_Histogram.setText(_translate("MainWindow", "Equalize Histogram"))


